-- PASSENGER & FLIGHT ENTITIES ARE USED (FOR NOW)
DROP TABLE IF EXISTS FLIGHTS;
CREATE TABLE FLIGHTS(
    ID INTEGER NOT NULL IDENTITY,
    AIRLINE VARCHAR(50) NOT NULL,
    FLIGHT_NUMBER VARCHAR(25) NOT NULL,
    FLIGHT_TYPE VARCHAR(25) NOT NULL,
    DEPARTURE VARCHAR(50) NOT NULL,
    ARRIVAL VARCHAR(50) NOT NULL,
    DATE DATE NOT NULL,
    ON_TIME BOOLEAN NOT NULL
);

DROP TABLE IF EXISTS PASSENGERS;
CREATE TABLE PASSENGERS(
    ID INTEGER NOT NULL IDENTITY,
    NAME VARCHAR(100) NOT NULL,
    AGE INTEGER NOT NULL,
    GENDER VARCHAR(20) NOT NULL,
    TRANSIT BOOLEAN NOT NULL,
    FLIGHTS INTEGER
);